CREATE PUBLIC SYNONYM PURCHASING_HIERARCHY_DDL      FOR VNC.PURCHASING_HIERARCHY_DDL@solar_gdwp2;
   
CREATE PUBLIC SYNONYM PURCHASING_HIERARCHY_CODES    FOR VNC.PURCHASING_HIERARCHY_CODES@solar_gdwp2;
   
CREATE PUBLIC SYNONYM PURCHASING_HIER_ASSOCIATES    FOR VNC.PURCHASING_HIER_ASSOCIATES@solar_gdwp2;
   
CREATE PUBLIC SYNONYM PURCHASING_HIERARCHY_TYPES    FOR VNC.PURCHASING_HIERARCHY_TYPES@solar_gdwp2;
   
CREATE PUBLIC SYNONYM BUYER_ASSOCIATES              FOR VNC.BUYER_ASSOCIATES@solar_gdwp2;
   
CREATE PUBLIC SYNONYM GBL_LGL_ORG_DRILL_DOWN_LAYERS FOR GBL_CURRENT.GBL_LGL_ORG_DRILL_DOWN_LAYERS@solar_gdwp2;
   
CREATE PUBLIC SYNONYM GBL_ORGS                      FOR GBL_CURRENT.GBL_ORGS@solar_gdwp2;
   
CREATE PUBLIC SYNONYM GBL_LEGAL_ORGS                FOR GBL_CURRENT.GBL_LEGAL_ORGS@solar_gdwp2;

CREATE PUBLIC SYNONYM GED_PUBLIC_TABLE              FOR GED.GED_PUBLIC_TABLE@solar_gdwp2;

CREATE PUBLIC SYNONYM PURCHASING_DOCUMENT_HEADERS   FOR SRS.PURCHASING_DOCUMENT_HEADERS@solar_gdwp2;
