-- RUN AS ESP_SOURCE@ecmdbq01_ecm01

CREATE PUBLIC SYNONYM TED_SDA_SUPPLIERS           FOR SDA.SDA_SUPPLIERS@SCORPION_GDWV2;
CREATE PUBLIC SYNONYM TED_SUPPLIER_PARTS          FOR SDA.SUPPLIER_PARTS@SCORPION_GDWV2;
CREATE PUBLIC SYNONYM TED_DIST_ERP_SUPPLIER_PARTS FOR SDA.DISTINCT_ERP_SUPPLIER_PARTS@SCORPION_GDWV2;

CREATE PUBLIC SYNONYM VW_SUPPLIER_USERS_PERMS     FOR STM_LDAP_STORE.VW_SUPPLIER_USERS_PERMS@STM_QA;
