CREATE PUBLIC SYNONYM PURCHASING_HIERARCHY_DDL      FOR VNC.PURCHASING_HIERARCHY_DDL@scorpion_gdwv2;
   
CREATE PUBLIC SYNONYM PURCHASING_HIERARCHY_CODES    FOR VNC.PURCHASING_HIERARCHY_CODES@scorpion_gdwv2;
   
CREATE PUBLIC SYNONYM PURCHASING_HIER_ASSOCIATES    FOR VNC.PURCHASING_HIER_ASSOCIATES@scorpion_gdwv2;
   
CREATE PUBLIC SYNONYM PURCHASING_HIERARCHY_TYPES    FOR VNC.PURCHASING_HIERARCHY_TYPES@scorpion_gdwv2;
   
CREATE PUBLIC SYNONYM BUYER_ASSOCIATES              FOR VNC.BUYER_ASSOCIATES@scorpion_gdwv2;
   
CREATE PUBLIC SYNONYM GBL_LGL_ORG_DRILL_DOWN_LAYERS FOR GBL_CURRENT.GBL_LGL_ORG_DRILL_DOWN_LAYERS@scorpion_gdwv2;
   
CREATE PUBLIC SYNONYM GBL_ORGS                      FOR GBL_CURRENT.GBL_ORGS@scorpion_gdwv2;
   
CREATE PUBLIC SYNONYM GBL_LEGAL_ORGS                FOR GBL_CURRENT.GBL_LEGAL_ORGS@scorpion_gdwv2;

CREATE PUBLIC SYNONYM GED_PUBLIC_TABLE              FOR GED.GED_PUBLIC_TABLE@scorpion_gdwv2;

CREATE PUBLIC SYNONYM PURCHASING_DOCUMENT_HEADERS   FOR SRS.PURCHASING_DOCUMENT_HEADERS@scorpion_gdwv2;

