CREATE OR REPLACE FUNCTION FUNC_NBR(AMP_PART_NBR VARCHAR2)
RETURN VARCHAR2 IS
	RET_PART_NBR CHAR(11);
BEGIN
	RET_PART_NBR := SUBSTR(AMP_PART_NBR,8,1) ||'-'|| SUBSTR(AMP_PART_NBR,1,7) ||'-'|| SUBSTR(AMP_PART_NBR,9,1) ;
  	RETURN RET_PART_NBR;
END Func_Nbr;
/
