connect SYS/change_on_install as SYSDBA
set echo on
spool /oracle/oradata/admin/SID/create/CreateDBTblspcFiles.log


CREATE TABLESPACE "SCM_INTERFACE_DATA"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_scm_interface_data' SIZE 200M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_ITEM_DATA"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_item_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_LOG_DATA"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_log_data01' SIZE 50M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_SYS_COMP_DATA"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_cce_syscmp01' SIZE 200M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE "SCM_INTERFACE_INDEX"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_scm_interface_idx01' SIZE 50M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_ITEM_INDEX"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_item_idx01' SIZE 50M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_LOG_INDEX"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_log_idx01' SIZE 10M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_SYS_COMP_INDEX"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_cce_syscmp_idx01' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 300M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_TEMP_DATA"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_cce_temp01' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_ARCH_DATA"
  LOGGING DATAFILE '/opt/db02/oradata/SID/SID_arch_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

spool off
exit;
