connect SYS/change_on_install as SYSDBA
set echo on
spool /opt/db01/app/oracle/admin/SID/create/CreateDBTblspcFiles.log


CREATE TABLESPACE "CCE_DVCE_IC_DATA"
  LOGGING DATAFILE '/u08/oradata/SID/SID_dvce_ic_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

--ALTER TABLESPACE "CCE_DVCE_IC_DATA"
--  ADD DATAFILE '/u08/oradata/SID/SID_dvce_ic_data02' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M;

CREATE TABLESPACE "CCE_DVCE_IC_HIST_DATA"
  LOGGING DATAFILE '/u08/oradata/SID/SID_dvce_ic_hist_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

--ALTER TABLESPACE "CCE_DVCE_IC_HIST_DATA"
--  ADD DATAFILE '/u08/oradata/SID/SID_dvce_ic_hist_data02' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 2000M;

CREATE TABLESPACE "CCE_DVCE_ITEM_DATA"
  LOGGING DATAFILE '/u07/oradata/SID/SID_dvce_item_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

ALTER TABLESPACE "CCE_DVCE_ITEM_DATA"
  ADD DATAFILE '/u07/oradata/SID/SID_dvce_item_data02' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M;

CREATE TABLESPACE "CCE_DVCE_ITEM_HIST_DATA"
  LOGGING DATAFILE '/u08/oradata/SID/SID_dvce_item_hist_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  50M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_DVCE_ITEM_DNLD_HIST_DATA"
  LOGGING DATAFILE '/u08/oradata/SID/SID_dvce_item_dnld_data01' SIZE 5M REUSE AUTOEXTEND ON NEXT  1M MAXSIZE 200M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_INTERFACE_DATA"
  LOGGING DATAFILE '/u06/oradata/SID/SID_scm_interface_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_ITEM_DATA"
  LOGGING DATAFILE '/u09/oradata/SID/SID_item_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_LOG_DATA"
  LOGGING DATAFILE '/u09/oradata/SID/SID_log_data01' SIZE 50M REUSE AUTOEXTEND ON NEXT  50M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_SUBSCRIBER_DATA"
  LOGGING DATAFILE '/u06/oradata/SID/SID_subscriber_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

--ALTER TABLESPACE "CCE_SUBSCRIBER_DATA"
--  ADD DATAFILE '/u06/oradata/SID/SID_subscriber_data02' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 2000M;

CREATE TABLESPACE "CCE_SYS_COMP_DATA"
  LOGGING DATAFILE '/u09/oradata/SID/SID_cce_syscmp01' SIZE 200M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_DVCE_IC_INDEX"
  LOGGING DATAFILE '/u19/oradata/SID/SID_dvce_ic_idx01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_DVCE_IC_HIST_INDEX"
  LOGGING DATAFILE '/u19/oradata/SID/SID_dvce_ic_hist_idx01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_DVCE_ITEM_INDEX"
  LOGGING DATAFILE '/u18/oradata/SID/SID_dvce_item_idx01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

ALTER TABLESPACE "CCE_DVCE_ITEM_INDEX"
  ADD DATAFILE '/u18/oradata/SID/SID_dvce_item_idx02' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M;

CREATE TABLESPACE "CCE_DVCE_ITEM_HIST_INDEX"
  LOGGING DATAFILE '/u18/oradata/SID/SID_dvce_item_hist_idx01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_DVCE_ITEM_DNLD_HIST_INDEX"
  LOGGING DATAFILE '/u18/oradata/SID/SID_dvce_item_dnld_idx01' SIZE 20M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_INTERFACE_INDEX"
  LOGGING DATAFILE '/u18/oradata/SID/SID_scm_interface_idx01' SIZE 50M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_ITEM_INDEX"
  LOGGING DATAFILE '/u18/oradata/SID/SID_item_idx01' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 200M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_LOG_INDEX"
  LOGGING DATAFILE '/u18/oradata/SID/SID_log_idx01' SIZE 100M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_SYS_COMP_INDEX"
  LOGGING DATAFILE '/u19/oradata/SID/SID_cce_syscmp_idx01' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 200M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_SUBSCRIBER_INDEX"
  LOGGING DATAFILE '/u17/oradata/SID/SID_subscriber_idx01' SIZE 2000M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_TEMP_DATA"
  LOGGING DATAFILE '/u10/oradata/SID/SID_cce_temp01' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "CCE_ARCH_DATA"
  LOGGING DATAFILE '/u10/oradata/SID/SID_arch_data01' SIZE 500M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR1_DATA"
  LOGGING DATAFILE '/u01/oradata/SID/SID_scm_ipdr1_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR2_DATA"
  LOGGING DATAFILE '/u01/oradata/SID/SID_scm_ipdr2_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR3_DATA"
  LOGGING DATAFILE '/u01/oradata/SID/SID_scm_ipdr3_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR4_DATA"
  LOGGING DATAFILE '/u01/oradata/SID/SID_scm_ipdr4_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR5_DATA"
  LOGGING DATAFILE '/u01/oradata/SID/SID_scm_ipdr5_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR6_DATA"
  LOGGING DATAFILE '/u02/oradata/SID/SID_scm_ipdr6_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR7_DATA"
  LOGGING DATAFILE '/u02/oradata/SID/SID_scm_ipdr7_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR8_DATA"
  LOGGING DATAFILE '/u02/oradata/SID/SID_scm_ipdr8_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR9_DATA"
  LOGGING DATAFILE '/u02/oradata/SID/SID_scm_ipdr9_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR10_DATA"
  LOGGING DATAFILE '/u02/oradata/SID/SID_scm_ipdr10_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR11_DATA"
  LOGGING DATAFILE '/u03/oradata/SID/SID_scm_ipdr11_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR12_DATA"
  LOGGING DATAFILE '/u03/oradata/SID/SID_scm_ipdr12_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR13_DATA"
  LOGGING DATAFILE '/u03/oradata/SID/SID_scm_ipdr13_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR14_DATA"
  LOGGING DATAFILE '/u03/oradata/SID/SID_scm_ipdr14_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR15_DATA"
  LOGGING DATAFILE '/u03/oradata/SID/SID_scm_ipdr15_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR16_DATA"
  LOGGING DATAFILE '/u04/oradata/SID/SID_scm_ipdr16_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR17_DATA"
  LOGGING DATAFILE '/u04/oradata/SID/SID_scm_ipdr17_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR18_DATA"
  LOGGING DATAFILE '/u04/oradata/SID/SID_scm_ipdr18_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR19_DATA"
  LOGGING DATAFILE '/u04/oradata/SID/SID_scm_ipdr19_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR20_DATA"
  LOGGING DATAFILE '/u04/oradata/SID/SID_scm_ipdr20_data_01' SIZE 2000M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "SCM_IPDR1_INDEX"
  LOGGING DATAFILE '/u05/oradata/SID/SID_scm_ipdr1_idx_01' SIZE 50M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

spool off
exit;
