CREATE OR REPLACE FUNCTION IS_NBR(I_VAL VARCHAR2)
RETURN NUMBER IS
	C_VAL VARCHAR2(20);
BEGIN
	C_VAL := SUBSTR(I_VAL,1,LENGTH(I_VAL)-4);
	C_VAL := SUBSTR(C_VAL,4,LENGTH(C_VAL)-3);
  	RETURN TO_NUMBER(C_VAL);
EXCEPTION
	WHEN OTHERS THEN
		 RETURN 0;
END;
/
