ALTER TABLE E01_CORPORATE_PARTS
ADD CONSTRAINT E01_CORPORATE_PARTS_PK
PRIMARY KEY (PART_KEY_ID)
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

CREATE INDEX E01_CORPORATE_PARTS_PF4
ON E01_CORPORATE_PARTS (TYCO_ELECTRONICS_CORP_PART_NBR, PART_KEY_ID)
TABLESPACE MPS_SAP_INDEX_A
PARALLEL 4;

ALTER INDEX E01_CORPORATE_PARTS_PF4
NOPARALLEL;

ALTER TABLE E01_GBL_PRODUCT
ADD CONSTRAINT E01_GBL_PRODUCT_PK               
PRIMARY KEY ( PROD_CODE )
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

ALTER TABLE E01_GBL_SAP_PROFIT_CENTERS 
ADD CONSTRAINT E01_GBL_SAP_PROFIT_CENTERS_PK 
PRIMARY KEY ( SAP_PROFIT_CENTER_CDE, SAP_PROFIT_CENTER_SOURCE_ID)
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

ALTER TABLE E01_MATERIAL_PLANTS 
ADD CONSTRAINT E01_MATERIAL_PLANTS_PK
PRIMARY KEY ( MATERIAL_ID, PLANT_ID )
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

ALTER TABLE E01_MATERIALS 
ADD CONSTRAINT E01_MATERIALS_PK
PRIMARY KEY ( MATERIAL_ID )
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

ALTER TABLE E01_MATERIAL_VALUATIONS 
ADD CONSTRAINT E01_MATERIAL_VALUATIONS_PK       
PRIMARY KEY ( MATERIAL_ID, VALUATION_AREA_ID, VALUATION_TYPE_CDE )
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

ALTER TABLE E01_MATERIAL_SLS_ORGS 
ADD CONSTRAINT E01_MATERIAL_SLS_ORGS_PK
PRIMARY KEY ( MATERIAL_ID, SALES_ORGANIZATION_ID, DISTRIBUTION_CHANNEL_CDE )
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

ALTER TABLE E01_SOURCE_LISTS 
ADD CONSTRAINT E01_SOURCE_LISTS_PK              
PRIMARY KEY ( MATERIAL_ID, PLANT_ID, SOURCE_LIST_SEQ_ID, SOURCE_SYSTEM_ID )
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

ALTER TABLE E01_ORGANIZATIONS_DMN 
ADD CONSTRAINT E01_ORGANIZATIONS_DMN_UK1
UNIQUE ( ORGANIZATION_KEY_ID, EFFECTIVE_FROM_DT)
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

ALTER TABLE E01_VENDORS
ADD CONSTRAINT E01_VENDORS_PK                   
PRIMARY KEY ( SOURCE_SYSTEM_ID, VENDOR_ID)
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

ALTER TABLE E01_VENDORS_DMN
ADD CONSTRAINT E01_VENDORS_DMN_PK
PRIMARY KEY ( VENDORS_KEY_ID, EFFECTIVE_TO_DT, EFFECTIVE_FROM_DT)
USING INDEX
TABLESPACE MPS_SAP_INDEX_A;

CREATE INDEX E01_VENDORS_DMN_PF2
ON E01_VENDORS_DMN
( SOURCE_SYSTEM_ID, VENDOR_ID) 
TABLESPACE MPS_SAP_INDEX_A 
PARALLEL 4;

ALTER INDEX E01_VENDORS_DMN_PF2 NOPARALLEL;