-- Connect to MPS_SAP

-- GRANT SELECT ON CL4_* Tables

GRANT SELECT ON MPS_SAP.CL4_BOM_HEADERS_V              TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_BOM_ITEMS_V                TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_CORPORATE_PARTS            TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_EQUIPMENT_MAIN_DATA_V      TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_FDC_SCHD_AGREEMENT_KINEXIS TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_GBL_IND_DRILL_DOWN_LAYERS  TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_GBL_MGE_PROFIT_CENTER_RELS TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_GBL_PRODUCT                TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_GBL_PRODUCT_LINE           TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_GBL_SAP_PROFIT_CENTERS     TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_GLOBAL_INVENTORIES_DAILY   TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_INFOREC_PUR_ORGS           TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_MASTER_CODES               TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_MATERIAL_PLANTS            TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_MATERIAL_SLS_ORGS          TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_MATERIAL_VALUATIONS        TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_MATERIALS                  TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_MATL_MFG_BLDG_XREF         TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_MFR_EFF_REPT_DETAILS       TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_OPERATIONS_CAPACITY_REQR   TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_OPERATIONS_SCHEDULING      TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_ORDER_ITEM_OPEN            TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_ORDER_ITEM_SHIPMENT        TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_ORGANIZATIONS_DMN          TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_PLANNED_PROD_ORDERS_V      TO MPS_SOURCE;
-- GRANT SELECT ON MPS_SAP.CL4_PROD_ORDER_DPNT_REQR       TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_PROD_ORDERS_HEADERS_V      TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_PROD_ORDERS_OPERATIONS_V   TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_PRODUCTION_ORDERS	       TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_PROD_PLANNING_VERSIONS_V   TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_ROUTING_OPERATIONS_V       TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_SOURCE_LISTS               TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_VENDOR_CONTACTS_V          TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_VENDORS                    TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_VENDORS_DMN                TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_WORK_CENTER_CAPACITIES_V   TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_WORK_CENTER_HEADERS_V      TO MPS_SOURCE;
GRANT SELECT ON MPS_SAP.CL4_WORK_CENTERS_HEIR_TREE     TO MPS_SOURCE;

-- Connect to MPS_SOURCE

-- DROP SYNONYMS ON CL4_* Tables

DROP SYNONYM MPS_SOURCE.BOM_HEADERS_V;      
DROP SYNONYM MPS_SOURCE.BOM_ITEMS_V;
DROP SYNONYM MPS_SOURCE.CORPORATE_PARTS;
DROP SYNONYM MPS_SOURCE.EQUIPMENT_MAIN_DATA_V;
DROP SYNONYM MPS_SOURCE.FDC_SCHEDULING_AGREEMENTS;
DROP SYNONYM MPS_SOURCE.GBL_INDUSTRY_DRILL_DOWN_LAYERS;
DROP SYNONYM MPS_SOURCE.GBL_MGE_PROFIT_CENTER_RELS;
DROP SYNONYM MPS_SOURCE.GBL_PRODUCT;
DROP SYNONYM MPS_SOURCE.GBL_PRODUCT_LINE;
DROP SYNONYM MPS_SOURCE.GBL_SAP_PROFIT_CENTERS;
DROP SYNONYM MPS_SOURCE.GLOBAL_INVENTORIES_DAILY;
DROP SYNONYM MPS_SOURCE.INFOREC_PUR_ORGS;
DROP SYNONYM MPS_SOURCE.MASTER_CODES;
DROP SYNONYM MPS_SOURCE.MATERIAL_PLANTS;
DROP SYNONYM MPS_SOURCE.MATERIAL_SLS_ORGS;
DROP SYNONYM MPS_SOURCE.MATERIAL_VALUATIONS;
DROP SYNONYM MPS_SOURCE.MATERIALS;
DROP SYNONYM MPS_SOURCE.MATL_MFG_BLDG_XREF;
DROP SYNONYM MPS_SOURCE.MFR_EFFICIENCY_REPT_DETAILS; 
DROP SYNONYM MPS_SOURCE.OPERATIONS_CAPACITY_REQR;
DROP SYNONYM MPS_SOURCE.OPERATIONS_SCHEDULING;
DROP SYNONYM MPS_SOURCE.ORDER_ITEM_OPEN;
DROP SYNONYM MPS_SOURCE.ORDER_ITEM_SHIPMENT;
DROP SYNONYM MPS_SOURCE.ORGANIZATIONS_DMN;
DROP SYNONYM MPS_SOURCE.PLANNED_PRODUCTION_ORDERS_V;
-- DROP SYNONYM MPS_SOURCE.PROD_ORDER_DPNT_REQUIREMENTS;
DROP SYNONYM MPS_SOURCE.PROD_ORDERS_HEADERS_V;
DROP SYNONYM MPS_SOURCE.PROD_ORDERS_OPERATIONS_V;
DROP SYNONYM MPS_SOURCE.PRODUCTION_ORDERS;
DROP SYNONYM MPS_SOURCE.PRODUCTION_PLANNING_VERSIONS_V;
DROP SYNONYM MPS_SOURCE.ROUTING_OPERATIONS_V;
DROP SYNONYM MPS_SOURCE.SOURCE_LISTS;
DROP SYNONYM MPS_SOURCE.VENDOR_CONTACTS_V;
DROP SYNONYM MPS_SOURCE.VENDORS;
DROP SYNONYM MPS_SOURCE.VENDORS_DMN;
DROP SYNONYM MPS_SOURCE.WORK_CENTER_CAPACITIES_V;
DROP SYNONYM MPS_SOURCE.WORK_CENTER_HEADERS_V;
DROP SYNONYM MPS_SOURCE.WORK_CENTERS_HEIRARCHY_TREE;

-- CREATE SYNONYMS ON CL4_* Tables

CREATE SYNONYM BOM_HEADERS_V		        FOR MPS_SAP.CL4_BOM_HEADERS_V;
CREATE SYNONYM BOM_ITEMS_V			FOR MPS_SAP.CL4_BOM_ITEMS_V;
CREATE SYNONYM CORPORATE_PARTS			FOR MPS_SAP.CL4_CORPORATE_PARTS;
CREATE SYNONYM EQUIPMENT_MAIN_DATA_V		FOR MPS_SAP.CL4_EQUIPMENT_MAIN_DATA_V;
CREATE SYNONYM FDC_SCHEDULING_AGREEMENTS	FOR MPS_SAP.CL4_FDC_SCHD_AGREEMENT_KINEXIS;
CREATE SYNONYM GBL_INDUSTRY_DRILL_DOWN_LAYERS	FOR MPS_SAP.CL4_GBL_IND_DRILL_DOWN_LAYERS;
CREATE SYNONYM GBL_MGE_PROFIT_CENTER_RELS	FOR MPS_SAP.CL4_GBL_MGE_PROFIT_CENTER_RELS;
CREATE SYNONYM GBL_PRODUCT			FOR MPS_SAP.CL4_GBL_PRODUCT;
CREATE SYNONYM GBL_PRODUCT_LINE			FOR MPS_SAP.CL4_GBL_PRODUCT_LINE;
CREATE SYNONYM GBL_SAP_PROFIT_CENTERS		FOR MPS_SAP.CL4_GBL_SAP_PROFIT_CENTERS;
CREATE SYNONYM GLOBAL_INVENTORIES_DAILY		FOR MPS_SAP.CL4_GLOBAL_INVENTORIES_DAILY;
CREATE SYNONYM INFOREC_PUR_ORGS			FOR MPS_SAP.CL4_INFOREC_PUR_ORGS;
CREATE SYNONYM MASTER_CODES			FOR MPS_SAP.CL4_MASTER_CODES;
CREATE SYNONYM MATERIAL_PLANTS			FOR MPS_SAP.CL4_MATERIAL_PLANTS;
CREATE SYNONYM MATERIAL_SLS_ORGS		FOR MPS_SAP.CL4_MATERIAL_SLS_ORGS;
CREATE SYNONYM MATERIAL_VALUATIONS		FOR MPS_SAP.CL4_MATERIAL_VALUATIONS;
CREATE SYNONYM MATERIALS			FOR MPS_SAP.CL4_MATERIALS;
CREATE SYNONYM MATL_MFG_BLDG_XREF		FOR MPS_SAP.CL4_MATL_MFG_BLDG_XREF;
CREATE SYNONYM MFR_EFFICIENCY_REPT_DETAILS 	FOR MPS_SAP.CL4_MFR_EFF_REPT_DETAILS;
CREATE SYNONYM OPERATIONS_CAPACITY_REQR		FOR MPS_SAP.CL4_OPERATIONS_CAPACITY_REQR;
CREATE SYNONYM OPERATIONS_SCHEDULING		FOR MPS_SAP.CL4_OPERATIONS_SCHEDULING;
CREATE SYNONYM ORDER_ITEM_OPEN			FOR MPS_SAP.CL4_ORDER_ITEM_OPEN;
CREATE SYNONYM ORDER_ITEM_SHIPMENT		FOR MPS_SAP.CL4_ORDER_ITEM_SHIPMENT;
CREATE SYNONYM ORGANIZATIONS_DMN		FOR MPS_SAP.CL4_ORGANIZATIONS_DMN;
CREATE SYNONYM PLANNED_PRODUCTION_ORDERS_V	FOR MPS_SAP.CL4_PLANNED_PROD_ORDERS_V;
-- CREATE SYNONYM PROD_ORDER_DPNT_REQUIREMENTS	FOR MPS_SAP.CL4_PROD_ORDER_DPNT_REQR;
CREATE SYNONYM PROD_ORDERS_HEADERS_V		FOR MPS_SAP.CL4_PROD_ORDERS_HEADERS_V;
CREATE SYNONYM PROD_ORDERS_OPERATIONS_V		FOR MPS_SAP.CL4_PROD_ORDERS_OPERATIONS_V;
CREATE SYNONYM PRODUCTION_ORDERS		FOR MPS_SAP.CL4_PRODUCTION_ORDERS;
CREATE SYNONYM PRODUCTION_PLANNING_VERSIONS_V	FOR MPS_SAP.CL4_PROD_PLANNING_VERSIONS_V;
CREATE SYNONYM ROUTING_OPERATIONS_V		FOR MPS_SAP.CL4_ROUTING_OPERATIONS_V;
CREATE SYNONYM SOURCE_LISTS			FOR MPS_SAP.CL4_SOURCE_LISTS;
CREATE SYNONYM VENDOR_CONTACTS_V		FOR MPS_SAP.CL4_VENDOR_CONTACTS_V;
CREATE SYNONYM VENDORS				FOR MPS_SAP.CL4_VENDORS;
CREATE SYNONYM VENDORS_DMN			FOR MPS_SAP.CL4_VENDORS_DMN;
CREATE SYNONYM WORK_CENTER_CAPACITIES_V		FOR MPS_SAP.CL4_WORK_CENTER_CAPACITIES_V;
CREATE SYNONYM WORK_CENTER_HEADERS_V		FOR MPS_SAP.CL4_WORK_CENTER_HEADERS_V;
CREATE SYNONYM WORK_CENTERS_HEIRARCHY_TREE	FOR MPS_SAP.CL4_WORK_CENTERS_HEIR_TREE;