-- Connect to MPS_SAP

-- Create Views:

CREATE OR REPLACE VIEW 	BOM_HEADERS_V               AS (SELECT * FROM CL2_BOM_HEADERS_V              UNION ALL SELECT * FROM CL4_BOM_HEADERS_V             );
CREATE OR REPLACE VIEW 	BOM_ITEMS_V		    AS (SELECT * FROM CL2_BOM_ITEMS_V		     UNION ALL SELECT * FROM CL4_BOM_ITEMS_V		   );
CREATE OR REPLACE VIEW 	CORPORATE_PARTS		    AS (SELECT * FROM CL2_CORPORATE_PARTS	     UNION ALL SELECT * FROM CL4_CORPORATE_PARTS	   );
CREATE OR REPLACE VIEW 	EQUIPMENT_MAIN_DATA_V	    AS (SELECT * FROM CL2_EQUIPMENT_MAIN_DATA_V	     UNION ALL SELECT * FROM CL4_EQUIPMENT_MAIN_DATA_V	   );
CREATE OR REPLACE VIEW 	FDC_SCHD_AGREEMENT_KINEXIS  AS (SELECT * FROM CL2_FDC_SCHD_AGREEMENT_KINEXIS UNION ALL SELECT * FROM CL4_FDC_SCHD_AGREEMENT_KINEXIS);
CREATE OR REPLACE VIEW 	GBL_IND_DRILL_DOWN_LAYERS   AS (SELECT * FROM CL2_GBL_IND_DRILL_DOWN_LAYERS  UNION ALL SELECT * FROM CL4_GBL_IND_DRILL_DOWN_LAYERS );
CREATE OR REPLACE VIEW 	GBL_MGE_PROFIT_CENTER_RELS  AS (SELECT * FROM CL2_GBL_MGE_PROFIT_CENTER_RELS UNION ALL SELECT * FROM CL4_GBL_MGE_PROFIT_CENTER_RELS);
CREATE OR REPLACE VIEW 	GBL_PRODUCT		    AS (SELECT * FROM CL2_GBL_PRODUCT		     UNION ALL SELECT * FROM CL4_GBL_PRODUCT		   );
CREATE OR REPLACE VIEW 	GBL_PRODUCT_LINE	    AS (SELECT * FROM CL2_GBL_PRODUCT_LINE	     UNION ALL SELECT * FROM CL4_GBL_PRODUCT_LINE	   );
CREATE OR REPLACE VIEW 	GBL_SAP_PROFIT_CENTERS	    AS (SELECT * FROM CL2_GBL_SAP_PROFIT_CENTERS     UNION ALL SELECT * FROM CL4_GBL_SAP_PROFIT_CENTERS	   );

CREATE OR REPLACE VIEW  GLOBAL_INVENTORIES_DAILY
AS (
SELECT reporting_organization_key_id, sbmt_reporting_organization_id, acquired_format_id, source_system_id, sap_profit_center_id, sbmt_material_number_id, part_key_id
     , sbmt_plant_id, plant_id, building_id, sbmt_storage_location_id, storage_location_id, sap_storage_location_id, inventory_location_id, warehouse_location_id
     , fiscal_month_end_dt, inventory_week_begin_dt, inventory_week_ending_dt, dml_user_id, dml_ts, batch_id, batch_record_id, stock_make_cde, unit_of_measure_cde
     , sbmt_unit_of_measure_cde, sbmt_original_inventory_qty, inventory_qty, stock_category_cde, special_stock_type_cde, sbmt_material_type_cde, material_type_cde
     , vendor_key_id, sbmt_vendor_id, batch_level_sequence_id, sap_mrp_group_cde, mrp_controller_cde, sap_origin_group_cde, last_activity_dt, sbmt_commodity_cde
     , commodity_key_id, sbmt_intraco_avbl_to_prom_cde, intraco_avbl_to_promise_cde, procurement_type_cde, local_iso_currency_cde, local_extn_standard_cost_amt
     , mge_profit_center_abbr_nm, true_frozen_cost_amt, labor_frozen_cost_amt, tot_ovhd_frozen_cost_amt, mfr_engr_frozen_cost_amt, true_matl_frozen_cost_amt
     , matl_brdn_frozen_cost_amt, intco_cntt_frozen_cost_amt, cnst_true_frozen_cost_amt, cnst_labor_frozen_cost_amt, cnst_tot_ovhd_frz_cost_amt, cnst_mfr_engr_frz_cost_amt
     , cnst_true_matl_frz_cost_amt, cnst_matl_brdn_frz_cost_amt, cnst_intco_cntt_frz_cost_amt, sbmt_buyer_id, buyer_key_id, sbmt_customer_account_nbr, st_acct_nbr_base
     , st_acct_nbr_sufx, customer_key_id, uom_conversion_reason_cde, cost_status_conversion_rsn_cde, cost_status_value_cnvr_rsn_cde, vendor_type_cde
     , sbmt_mge_profit_center_abbr_nm, cnst_local_extn_std_cost_amt, harmonization_cost_helper_cde, inventory_reporting_ind, manufacturing_source_org_id
     , tentative_stock_ptc_ind, part_prcr_source_org_id, hyperion_valuation_ind, data_extract_dt, sap_sales_order_nbr, sap_sales_order_item_nbr, inventory_dt
     , extn_auth_cost_amt, cnst_extn_auth_cost_amt
FROM CL2_GLOBAL_INVENTORIES_DAILY   
UNION ALL 
SELECT reporting_organization_key_id, sbmt_reporting_organization_id, acquired_format_id, source_system_id, sap_profit_center_id, sbmt_material_number_id, part_key_id
     , sbmt_plant_id, plant_id, building_id, sbmt_storage_location_id, storage_location_id, sap_storage_location_id, inventory_location_id, warehouse_location_id
     , fiscal_month_end_dt, inventory_week_begin_dt, inventory_week_ending_dt, dml_user_id, dml_ts, batch_id, batch_record_id, stock_make_cde, unit_of_measure_cde
     , sbmt_unit_of_measure_cde, sbmt_original_inventory_qty, inventory_qty, stock_category_cde, special_stock_type_cde, sbmt_material_type_cde, material_type_cde
     , vendor_key_id, sbmt_vendor_id, batch_level_sequence_id, sap_mrp_group_cde, mrp_controller_cde, sap_origin_group_cde, last_activity_dt, sbmt_commodity_cde
     , commodity_key_id, sbmt_intraco_avbl_to_prom_cde, intraco_avbl_to_promise_cde, procurement_type_cde, local_iso_currency_cde, local_extn_standard_cost_amt
     , mge_profit_center_abbr_nm, true_frozen_cost_amt, labor_frozen_cost_amt, tot_ovhd_frozen_cost_amt, mfr_engr_frozen_cost_amt, true_matl_frozen_cost_amt
     , matl_brdn_frozen_cost_amt, intco_cntt_frozen_cost_amt, cnst_true_frozen_cost_amt, cnst_labor_frozen_cost_amt, cnst_tot_ovhd_frz_cost_amt, cnst_mfr_engr_frz_cost_amt
     , cnst_true_matl_frz_cost_amt, cnst_matl_brdn_frz_cost_amt, cnst_intco_cntt_frz_cost_amt, sbmt_buyer_id, buyer_key_id, sbmt_customer_account_nbr, st_acct_nbr_base
     , st_acct_nbr_sufx, customer_key_id, uom_conversion_reason_cde, cost_status_conversion_rsn_cde, cost_status_value_cnvr_rsn_cde, vendor_type_cde
     , sbmt_mge_profit_center_abbr_nm, cnst_local_extn_std_cost_amt, harmonization_cost_helper_cde, inventory_reporting_ind, manufacturing_source_org_id
     , tentative_stock_ptc_ind, part_prcr_source_org_id, hyperion_valuation_ind, data_extract_dt, sap_sales_order_nbr, sap_sales_order_item_nbr, inventory_dt
     , NULL EXTN_AUTH_COST_AMT, NULL CNST_EXTN_AUTH_COST_AMT 
FROM CL4_GLOBAL_INVENTORIES_DAILY  );

CREATE OR REPLACE VIEW 	INFOREC_PUR_ORGS	    AS (SELECT * FROM CL2_INFOREC_PUR_ORGS	     UNION ALL SELECT * FROM CL4_INFOREC_PUR_ORGS	   );
CREATE OR REPLACE VIEW 	MASTER_CODES		    AS (SELECT * FROM CL2_MASTER_CODES		     UNION ALL SELECT * FROM CL4_MASTER_CODES		   );
CREATE OR REPLACE VIEW 	MATERIALS		    AS (SELECT * FROM CL2_MATERIALS		     UNION ALL SELECT * FROM CL4_MATERIALS		   );
CREATE OR REPLACE VIEW 	MATERIAL_PLANTS		    AS (SELECT * FROM CL2_MATERIAL_PLANTS	     UNION ALL SELECT * FROM CL4_MATERIAL_PLANTS	   );
CREATE OR REPLACE VIEW 	MATERIAL_SLS_ORGS	    AS (SELECT * FROM CL2_MATERIAL_SLS_ORGS	     UNION ALL SELECT * FROM CL4_MATERIAL_SLS_ORGS	   );
CREATE OR REPLACE VIEW 	MATERIAL_VALUATIONS	    AS (SELECT * FROM CL2_MATERIAL_VALUATIONS	     UNION ALL SELECT * FROM CL4_MATERIAL_VALUATIONS	   );
CREATE OR REPLACE VIEW 	MATL_MFG_BLDG_XREF	    AS (SELECT * FROM CL2_MATL_MFG_BLDG_XREF	     UNION ALL SELECT * FROM CL4_MATL_MFG_BLDG_XREF	   );
CREATE OR REPLACE VIEW 	MFR_EFF_REPT_DETAILS	    AS (SELECT * FROM CL2_MFR_EFF_REPT_DETAILS	     UNION ALL SELECT * FROM CL4_MFR_EFF_REPT_DETAILS	   );
CREATE OR REPLACE VIEW 	OPERATIONS_CAPACITY_REQR    AS (SELECT * FROM CL2_OPERATIONS_CAPACITY_REQR   UNION ALL SELECT * FROM CL4_OPERATIONS_CAPACITY_REQR  );
CREATE OR REPLACE VIEW 	OPERATIONS_SCHEDULING	    AS (SELECT * FROM CL2_OPERATIONS_SCHEDULING	     UNION ALL SELECT * FROM CL4_OPERATIONS_SCHEDULING	   );
CREATE OR REPLACE VIEW 	ORDER_ITEM_OPEN		    AS (SELECT * FROM CL2_ORDER_ITEM_OPEN	     UNION ALL SELECT * FROM CL4_ORDER_ITEM_OPEN	   );
CREATE OR REPLACE VIEW 	ORDER_ITEM_SHIPMENT	    AS (SELECT * FROM CL2_ORDER_ITEM_SHIPMENT	     UNION ALL SELECT * FROM CL4_ORDER_ITEM_SHIPMENT	   );
CREATE OR REPLACE VIEW 	ORGANIZATIONS_DMN	    AS (SELECT * FROM CL2_ORGANIZATIONS_DMN	     UNION ALL SELECT * FROM CL4_ORGANIZATIONS_DMN	   );
CREATE OR REPLACE VIEW 	PLANNED_PROD_ORDERS_V	    AS (SELECT * FROM CL2_PLANNED_PROD_ORDERS_V	     UNION ALL SELECT * FROM CL4_PLANNED_PROD_ORDERS_V	   );
CREATE OR REPLACE VIEW 	PRODUCTION_ORDERS	    AS (SELECT * FROM CL2_PRODUCTION_ORDERS	     UNION ALL SELECT * FROM CL4_PRODUCTION_ORDERS	   );
CREATE OR REPLACE VIEW 	PROD_ORDERS_HEADERS_V	    AS (SELECT * FROM CL2_PROD_ORDERS_HEADERS_V	     UNION ALL SELECT * FROM CL4_PROD_ORDERS_HEADERS_V	   );
CREATE OR REPLACE VIEW 	PROD_ORDERS_OPERATIONS_V    AS (SELECT * FROM CL2_PROD_ORDERS_OPERATIONS_V   UNION ALL SELECT * FROM CL4_PROD_ORDERS_OPERATIONS_V  );
CREATE OR REPLACE VIEW 	PROD_ORDER_DPNT_REQ	    AS (SELECT * FROM CL2_PROD_ORDER_DPNT_REQ	     UNION ALL SELECT * FROM CL4_PROD_ORDER_DPNT_REQ	   );
CREATE OR REPLACE VIEW 	PROD_PLANNING_VERSIONS_V    AS (SELECT * FROM CL2_PROD_PLANNING_VERSIONS_V   UNION ALL SELECT * FROM CL4_PROD_PLANNING_VERSIONS_V  );
CREATE OR REPLACE VIEW 	ROUTING_OPERATIONS_V	    AS (SELECT * FROM CL2_ROUTING_OPERATIONS_V	     UNION ALL SELECT * FROM CL4_ROUTING_OPERATIONS_V	   );
CREATE OR REPLACE VIEW 	SOURCE_LISTS		    AS (SELECT * FROM CL2_SOURCE_LISTS		     UNION ALL SELECT * FROM CL4_SOURCE_LISTS		   );
CREATE OR REPLACE VIEW 	VENDORS			    AS (SELECT * FROM CL2_VENDORS		     UNION ALL SELECT * FROM CL4_VENDORS		   );
CREATE OR REPLACE VIEW 	VENDORS_DMN		    AS (SELECT * FROM CL2_VENDORS_DMN		     UNION ALL SELECT * FROM CL4_VENDORS_DMN		   );
CREATE OR REPLACE VIEW 	VENDOR_CONTACTS_V	    AS (SELECT * FROM CL2_VENDOR_CONTACTS_V	     UNION ALL SELECT * FROM CL4_VENDOR_CONTACTS_V	   );
CREATE OR REPLACE VIEW 	WORK_CENTERS_HEIR_TREE	    AS (SELECT * FROM CL2_WORK_CENTERS_HEIR_TREE     UNION ALL SELECT * FROM CL4_WORK_CENTERS_HEIR_TREE	   );
CREATE OR REPLACE VIEW 	WORK_CENTER_CAPACITIES_V    AS (SELECT * FROM CL2_WORK_CENTER_CAPACITIES_V   UNION ALL SELECT * FROM CL4_WORK_CENTER_CAPACITIES_V  );
CREATE OR REPLACE VIEW 	WORK_CENTER_HEADERS_V	    AS (SELECT * FROM CL2_WORK_CENTER_HEADERS_V	     UNION ALL SELECT * FROM CL4_WORK_CENTER_HEADERS_V	   );

-- Grants


GRANT SELECT ON BOM_HEADERS_V               TO MPS_SOURCE;
GRANT SELECT ON BOM_ITEMS_V		    TO MPS_SOURCE;
GRANT SELECT ON CORPORATE_PARTS		    TO MPS_SOURCE;
GRANT SELECT ON EQUIPMENT_MAIN_DATA_V	    TO MPS_SOURCE;
GRANT SELECT ON FDC_SCHD_AGREEMENT_KINEXIS  TO MPS_SOURCE;
GRANT SELECT ON GBL_IND_DRILL_DOWN_LAYERS   TO MPS_SOURCE;
GRANT SELECT ON GBL_MGE_PROFIT_CENTER_RELS  TO MPS_SOURCE;
GRANT SELECT ON GBL_PRODUCT		    TO MPS_SOURCE;
GRANT SELECT ON GBL_PRODUCT_LINE	    TO MPS_SOURCE;
GRANT SELECT ON GBL_SAP_PROFIT_CENTERS	    TO MPS_SOURCE;
GRANT SELECT ON GLOBAL_INVENTORIES_DAILY    TO MPS_SOURCE;
GRANT SELECT ON INFOREC_PUR_ORGS	    TO MPS_SOURCE;
GRANT SELECT ON MASTER_CODES		    TO MPS_SOURCE;
GRANT SELECT ON MATERIALS		    TO MPS_SOURCE;
GRANT SELECT ON MATERIAL_PLANTS		    TO MPS_SOURCE;
GRANT SELECT ON MATERIAL_SLS_ORGS	    TO MPS_SOURCE;
GRANT SELECT ON MATERIAL_VALUATIONS	    TO MPS_SOURCE;
GRANT SELECT ON MATL_MFG_BLDG_XREF	    TO MPS_SOURCE;
GRANT SELECT ON MFR_EFF_REPT_DETAILS	    TO MPS_SOURCE;
GRANT SELECT ON OPERATIONS_CAPACITY_REQR    TO MPS_SOURCE;
GRANT SELECT ON OPERATIONS_SCHEDULING	    TO MPS_SOURCE;
GRANT SELECT ON ORDER_ITEM_OPEN		    TO MPS_SOURCE;
GRANT SELECT ON ORDER_ITEM_SHIPMENT	    TO MPS_SOURCE;
GRANT SELECT ON ORGANIZATIONS_DMN	    TO MPS_SOURCE;
GRANT SELECT ON PLANNED_PROD_ORDERS_V	    TO MPS_SOURCE;
GRANT SELECT ON PRODUCTION_ORDERS	    TO MPS_SOURCE;
GRANT SELECT ON PROD_ORDERS_HEADERS_V	    TO MPS_SOURCE;
GRANT SELECT ON PROD_ORDERS_OPERATIONS_V    TO MPS_SOURCE;
GRANT SELECT ON PROD_ORDER_DPNT_REQ	    TO MPS_SOURCE;
GRANT SELECT ON PROD_PLANNING_VERSIONS_V    TO MPS_SOURCE;
GRANT SELECT ON ROUTING_OPERATIONS_V	    TO MPS_SOURCE;
GRANT SELECT ON SOURCE_LISTS		    TO MPS_SOURCE;
GRANT SELECT ON VENDORS			    TO MPS_SOURCE;
GRANT SELECT ON VENDORS_DMN		    TO MPS_SOURCE;
GRANT SELECT ON VENDOR_CONTACTS_V	    TO MPS_SOURCE;
GRANT SELECT ON WORK_CENTERS_HEIR_TREE	    TO MPS_SOURCE;
GRANT SELECT ON WORK_CENTER_CAPACITIES_V    TO MPS_SOURCE;
GRANT SELECT ON WORK_CENTER_HEADERS_V	    TO MPS_SOURCE;

-- Connect to MPS_SOURCE

-- Drop Existing Synonyms

/*
DROP SYNONYM MPS_SOURCE.BOM_HEADERS_V            ;
DROP SYNONYM MPS_SOURCE.BOM_ITEMS_V		 ;
DROP SYNONYM MPS_SOURCE.CORPORATE_PARTS		 ;
DROP SYNONYM MPS_SOURCE.EQUIPMENT_MAIN_DATA_V	 ;
DROP SYNONYM MPS_SOURCE.FDC_SCHD_AGREEMENT_KINEXIS ;
DROP SYNONYM MPS_SOURCE.GBL_IND_DRILL_DOWN_LAYERS ;
DROP SYNONYM MPS_SOURCE.GBL_MGE_PROFIT_CENTER_RELS ;
DROP SYNONYM MPS_SOURCE.GBL_PRODUCT		 ;
DROP SYNONYM MPS_SOURCE.GBL_PRODUCT_LINE	 ;
DROP SYNONYM MPS_SOURCE.GBL_SAP_PROFIT_CENTERS	 ;
DROP SYNONYM MPS_SOURCE.GLOBAL_INVENTORIES_DAILY ;
DROP SYNONYM MPS_SOURCE.INFOREC_PUR_ORGS	 ;
DROP SYNONYM MPS_SOURCE.MASTER_CODES		 ;
DROP SYNONYM MPS_SOURCE.MATERIALS		 ;
DROP SYNONYM MPS_SOURCE.MATERIAL_PLANTS		 ;
DROP SYNONYM MPS_SOURCE.MATERIAL_SLS_ORGS	 ;
DROP SYNONYM MPS_SOURCE.MATERIAL_VALUATIONS	 ;
DROP SYNONYM MPS_SOURCE.MATL_MFG_BLDG_XREF	 ;
DROP SYNONYM MPS_SOURCE.MFR_EFF_REPT_DETAILS	 ;
DROP SYNONYM MPS_SOURCE.OPERATIONS_CAPACITY_REQR ;
DROP SYNONYM MPS_SOURCE.OPERATIONS_SCHEDULING	 ;
DROP SYNONYM MPS_SOURCE.ORDER_ITEM_OPEN		 ;
DROP SYNONYM MPS_SOURCE.ORDER_ITEM_SHIPMENT	 ;
DROP SYNONYM MPS_SOURCE.ORGANIZATIONS_DMN	 ;
DROP SYNONYM MPS_SOURCE.PLANNED_PROD_ORDERS_V	 ;
DROP SYNONYM MPS_SOURCE.PRODUCTION_ORDERS	 ;
DROP SYNONYM MPS_SOURCE.PROD_ORDERS_HEADERS_V	 ;
DROP SYNONYM MPS_SOURCE.PROD_ORDERS_OPERATIONS_V ;
DROP SYNONYM MPS_SOURCE.PROD_ORDER_DPNT_REQ	 ;
DROP SYNONYM MPS_SOURCE.PROD_PLANNING_VERSIONS_V ;
DROP SYNONYM MPS_SOURCE.ROUTING_OPERATIONS_V	 ;
DROP SYNONYM MPS_SOURCE.SOURCE_LISTS		 ;
DROP SYNONYM MPS_SOURCE.VENDORS			 ;
DROP SYNONYM MPS_SOURCE.VENDORS_DMN		 ;
DROP SYNONYM MPS_SOURCE.VENDOR_CONTACTS_V	 ;
DROP SYNONYM MPS_SOURCE.WORK_CENTERS_HEIR_TREE	 ;
DROP SYNONYM MPS_SOURCE.WORK_CENTER_CAPACITIES_V ;
DROP SYNONYM MPS_SOURCE.WORK_CENTER_HEADERS_V	 ;
*/


-- Create Synonyms

CREATE  SYNONYM BOM_HEADERS_V              FOR MPS_SAP.BOM_HEADERS_V             ;
CREATE  SYNONYM BOM_ITEMS_V		   FOR MPS_SAP.BOM_ITEMS_V		 ; 
CREATE  SYNONYM CORPORATE_PARTS		   FOR MPS_SAP.CORPORATE_PARTS		 ; 
CREATE  SYNONYM EQUIPMENT_MAIN_DATA_V	   FOR MPS_SAP.EQUIPMENT_MAIN_DATA_V	 ; 
CREATE  SYNONYM FDC_SCHD_AGREEMENT_KINEXIS FOR MPS_SAP.FDC_SCHD_AGREEMENT_KINEXIS;
CREATE  SYNONYM GBL_IND_DRILL_DOWN_LAYERS  FOR MPS_SAP.GBL_IND_DRILL_DOWN_LAYERS ; 
CREATE  SYNONYM GBL_MGE_PROFIT_CENTER_RELS FOR MPS_SAP.GBL_MGE_PROFIT_CENTER_RELS; 
CREATE  SYNONYM GBL_PRODUCT		   FOR MPS_SAP.GBL_PRODUCT		 ;
CREATE  SYNONYM GBL_PRODUCT_LINE	   FOR MPS_SAP.GBL_PRODUCT_LINE	 ;
CREATE  SYNONYM GBL_SAP_PROFIT_CENTERS	   FOR MPS_SAP.GBL_SAP_PROFIT_CENTERS	 ;
CREATE  SYNONYM GLOBAL_INVENTORIES_DAILY   FOR MPS_SAP.GLOBAL_INVENTORIES_DAILY ;
CREATE  SYNONYM INFOREC_PUR_ORGS	   FOR MPS_SAP.INFOREC_PUR_ORGS	 ;
CREATE  SYNONYM MASTER_CODES		   FOR MPS_SAP.MASTER_CODES		 ;
CREATE  SYNONYM MATERIALS		   FOR MPS_SAP.MATERIALS		 ;
CREATE  SYNONYM MATERIAL_PLANTS		   FOR MPS_SAP.MATERIAL_PLANTS		 ;
CREATE  SYNONYM MATERIAL_SLS_ORGS	   FOR MPS_SAP.MATERIAL_SLS_ORGS	 ;
CREATE  SYNONYM MATERIAL_VALUATIONS	   FOR MPS_SAP.MATERIAL_VALUATIONS	 ;
CREATE  SYNONYM MATL_MFG_BLDG_XREF	   FOR MPS_SAP.MATL_MFG_BLDG_XREF	 ;
CREATE  SYNONYM MFR_EFF_REPT_DETAILS	   FOR MPS_SAP.MFR_EFF_REPT_DETAILS	 ;
CREATE  SYNONYM OPERATIONS_CAPACITY_REQR   FOR MPS_SAP.OPERATIONS_CAPACITY_REQR ;
CREATE  SYNONYM OPERATIONS_SCHEDULING	   FOR MPS_SAP.OPERATIONS_SCHEDULING	 ;
CREATE  SYNONYM ORDER_ITEM_OPEN		   FOR MPS_SAP.ORDER_ITEM_OPEN		 ;
CREATE  SYNONYM ORDER_ITEM_SHIPMENT	   FOR MPS_SAP.ORDER_ITEM_SHIPMENT	 ;
CREATE  SYNONYM ORGANIZATIONS_DMN	   FOR MPS_SAP.ORGANIZATIONS_DMN	 ;
CREATE  SYNONYM PLANNED_PROD_ORDERS_V	   FOR MPS_SAP.PLANNED_PROD_ORDERS_V	 ;
CREATE  SYNONYM PRODUCTION_ORDERS	   FOR MPS_SAP.PRODUCTION_ORDERS	 ;
CREATE  SYNONYM PROD_ORDERS_HEADERS_V	   FOR MPS_SAP.PROD_ORDERS_HEADERS_V	 ;
CREATE  SYNONYM PROD_ORDERS_OPERATIONS_V   FOR MPS_SAP.PROD_ORDERS_OPERATIONS_V ;
CREATE  SYNONYM PROD_ORDER_DPNT_REQ	   FOR MPS_SAP.PROD_ORDER_DPNT_REQ	 ;
CREATE  SYNONYM PROD_PLANNING_VERSIONS_V   FOR MPS_SAP.PROD_PLANNING_VERSIONS_V ;
CREATE  SYNONYM ROUTING_OPERATIONS_V	   FOR MPS_SAP.ROUTING_OPERATIONS_V	 ;
CREATE  SYNONYM SOURCE_LISTS		   FOR MPS_SAP.SOURCE_LISTS		 ;
CREATE  SYNONYM VENDORS			   FOR MPS_SAP.VENDORS			 ;
CREATE  SYNONYM VENDORS_DMN		   FOR MPS_SAP.VENDORS_DMN		 ;
CREATE  SYNONYM VENDOR_CONTACTS_V	   FOR MPS_SAP.VENDOR_CONTACTS_V	 ;
CREATE  SYNONYM WORK_CENTERS_HEIR_TREE	   FOR MPS_SAP.WORK_CENTERS_HEIR_TREE	 ;
CREATE  SYNONYM WORK_CENTER_CAPACITIES_V   FOR MPS_SAP.WORK_CENTER_CAPACITIES_V ;
CREATE  SYNONYM WORK_CENTER_HEADERS_V	   FOR MPS_SAP.WORK_CENTER_HEADERS_V	 ;
