CREATE OR REPLACE VIEW SCD.ORDER_ITEM_SHIPMENT_CURRENT
(amp_order_nbr, order_item_nbr, shipment_id, dml_oracle_id, dml_tmstmp, purchase_by_account_base, ship_to_account_suffix, prodcn_cntrlr_code, item_quantity, resrvn_level_1, resrvn_level_5, resrvn_level_9, quantity_released, quantity_shipped, iso_currency_code_1, local_currency_billed_amount, extended_book_bill_amount, range_code, unit_price, customer_request_date, amp_schedule_date, release_date, actual_on_dock_date, amp_shipped_date, nbr_window_days_early, nbr_window_days_late, inventory_location_code, inventory_building_nbr, actual_ship_location, actual_ship_building_nbr, schedule_ship_cmprsn_code, schedule_to_ship_variance, varbl_schedule_ship_variance, request_ship_cmprsn_code, request_to_ship_variance, varbl_request_ship_variance, request_schedule_cmprsn_code, request_to_schedule_variance, current_to_request_variance, current_to_schedule_variance, received_to_request_variance, received_to_schedule_variance, received_to_ship_variance, varbl_received_ship_variance, release_to_schedule_variance, release_schedule_cmprsn_code, ship_facility_cmprsn_code, release_to_ship_variance, order_booking_date, order_received_date, order_type_id, regtrd_date, reported_as_of_date, database_load_date, inventory_classfcn_code, purchase_order_date, purchase_order_nbr, prodcn_cntlr_employee_nbr, schlg_method_code, team_code, stock_make_code, product_code, ww_account_nbr_base, ww_account_nbr_suffix, customer_forecast_code, a_territory_nbr, customer_reference_part_nbr, customer_expedite_date, nbr_of_expedites, original_expedite_date, current_expedite_date, earliest_expedite_date, schedule_on_credit_hold_date, schedule_off_credit_hold_date, customer_credit_hold_ind, customer_on_credit_hold_date, temp_hold_ind, temp_hold_on_date, temp_hold_off_date, forced_bill_ind, customer_type_code, rush_ind, industry_code, product_busns_line_id, product_busns_line_fnctn_id, mfg_campus_id, mfg_building_nbr, industry_business_code, fiscal_month, fiscal_quarter, fiscal_year, sbmt_part_nbr, sbmt_customer_acct_nbr, brand_id, profit_center_abbr_nm, schd_tyco_month_of_year_id, schd_tyco_quarter_id, schd_tyco_year_id, sold_to_customer_id, invoice_nbr, delivery_block_cde, credit_check_status_cde, sales_organization_id, distribution_channel_cde, order_division_cde, item_division_cde, matl_account_asgn_grp_cde, data_source_desc, batch_id, organization_key_id, mfr_org_key_id, accounting_org_key_id, customer_acct_type_cde, product_line_code, part_prcr_src_org_key_id, controller_uniqueness_id, prime_worldwide_customer_id, sales_document_type_cde, material_type_cde, drop_shipment_ind, sales_office_cde, sales_group_cde, scorecard_organization_id, group_organization_id, company_organization_id, accounting_organization_id, part_prcr_source_org_id, manufacturing_org_id, budget_rate_book_bill_amt, part_key_id, storage_location_id)
AS
SELECT ois.amp_order_nbr,
          ois.order_item_nbr,
          ois.shipment_id,
          ois.dml_oracle_id,
          ois.dml_tmstmp,
          ois.purchase_by_account_base,
          ois.ship_to_account_suffix,
          ois.prodcn_cntrlr_code,
          ois.item_quantity,
          ois.resrvn_level_1,
          ois.resrvn_level_5,
          ois.resrvn_level_9,
          ois.quantity_released,
          ois.quantity_shipped,
          ois.iso_currency_code_1,
          ois.local_currency_billed_amount,
          ois.extended_book_bill_amount,
          ois.range_code,
          ois.unit_price,
          ois.customer_request_date,
          ois.amp_schedule_date,
          ois.release_date,
          ois.actual_on_dock_date,
          ois.amp_shipped_date,
          ois.nbr_window_days_early,
          ois.nbr_window_days_late,
          ois.inventory_location_code,
          ois.inventory_building_nbr,
          ois.actual_ship_location,
          ois.actual_ship_building_nbr,
          ois.schedule_ship_cmprsn_code,
          ois.schedule_to_ship_variance,
          ois.varbl_schedule_ship_variance,
          ois.request_ship_cmprsn_code,
          ois.request_to_ship_variance,
          ois.varbl_request_ship_variance,
          ois.request_schedule_cmprsn_code,
          ois.request_to_schedule_variance,
          ois.current_to_request_variance,
          ois.current_to_schedule_variance,
          ois.received_to_request_variance,
          ois.received_to_schedule_variance,
          ois.received_to_ship_variance,
          ois.varbl_received_ship_variance,
          ois.release_to_schedule_variance,
          ois.release_schedule_cmprsn_code,
          ois.ship_facility_cmprsn_code,
          ois.release_to_ship_variance,
          ois.order_booking_date,
          ois.order_received_date,
          ois.order_type_id,
          ois.regtrd_date,
          ois.reported_as_of_date,
          ois.database_load_date,
          ois.inventory_classfcn_code,
          ois.purchase_order_date,
          ois.purchase_order_nbr,
          ois.prodcn_cntlr_employee_nbr,
          ois.schlg_method_code,
          ois.team_code,
          ois.stock_make_code,
          ois.product_code,
          ois.ww_account_nbr_base,
          ois.ww_account_nbr_suffix,
          ois.customer_forecast_code,
          ois.a_territory_nbr,
          ois.customer_reference_part_nbr,
          ois.customer_expedite_date,
          ois.nbr_of_expedites,
          ois.original_expedite_date,
          ois.current_expedite_date,
          ois.earliest_expedite_date,
          ois.schedule_on_credit_hold_date,
          ois.schedule_off_credit_hold_date,
          ois.customer_credit_hold_ind,
          ois.customer_on_credit_hold_date,
          ois.temp_hold_ind,
          ois.temp_hold_on_date,
          ois.temp_hold_off_date,
          ois.forced_bill_ind,
          ois.customer_type_code,
          ois.rush_ind,
          ois.industry_code,
          ois.product_busns_line_id,
          ois.product_busns_line_fnctn_id,
          ois.mfg_campus_id,
          ois.mfg_building_nbr,
          ois.industry_business_code,
          ois.fiscal_month,
          ois.fiscal_quarter,
          ois.fiscal_year,
          ois.sbmt_part_nbr,
          ois.sbmt_customer_acct_nbr,
          ois.brand_id,
          ois.profit_center_abbr_nm,
          ois.schd_tyco_month_of_year_id,
          ois.schd_tyco_quarter_id,
          ois.schd_tyco_year_id,
          ois.sold_to_customer_id,
          ois.invoice_nbr,
          ois.delivery_block_cde,
          ois.credit_check_status_cde,
          ois.sales_organization_id,
          ois.distribution_channel_cde,
          ois.order_division_cde,
          ois.item_division_cde,
          ois.matl_account_asgn_grp_cde,
          ois.data_source_desc,
          ois.batch_id,
          ois.organization_key_id,
          ois.mfr_org_key_id,
          ois.accounting_org_key_id,
          ois.customer_acct_type_cde,
          ois.product_line_code,
          ois.part_prcr_src_org_key_id,
          ois.controller_uniqueness_id,
          ois.prime_worldwide_customer_id,
          ois.sales_document_type_cde,
          ois.material_type_cde,
          ois.drop_shipment_ind,
          ois.sales_office_cde,
          ois.sales_group_cde,
          odim.organization_id,
          DECODE (odim.parent_organization_id,
                  odim.company_organization_id, odim.organization_id,
                  odim.parent_organization_id),
          odim.company_organization_id,
          accodim.organization_id,
          ppsodim.organization_id,
          mfrodim.organization_id,
          ois.budget_rate_book_bill_amt,
          ois.part_key_id,
          storage_location_id
          -- , ois.actual_on_customer_dock_date
	  -- , ois.customer_revised_schedule_date
	  -- , ois.end_cust_account_id
	  -- , ois.end_cust_purchase_order_id
	  -- , ois.end_cust_ww_account_id
	  -- , ois.inco_purchase_order_id
	  -- , ois.inco_purchase_order_item_id
	  -- , ois.pb_acct_org_id
	  -- , ois.purchased_from_org_id
	  -- , ois.purchasing_org_cde
	  -- , ois.schedule_on_customer_dock_date
	  -- , ois.special_packaging_code
     FROM order_item_shipment ois,
          organizations_dmn odim,
          organizations_dmn accodim,
          organizations_dmn ppsodim,
          organizations_dmn mfrodim
    WHERE     ois.organization_key_id = odim.organization_key_id
          AND odim.record_status_cde = 'C'
          AND odim.company_organization_id = '0048'
          AND ois.accounting_org_key_id = accodim.organization_key_id
          AND accodim.record_status_cde = 'C'
          AND ois.part_prcr_src_org_key_id = ppsodim.organization_key_id(+)
          AND ppsodim.record_status_cde(+) = 'C'
          AND ois.mfr_org_key_id = mfrodim.organization_key_id
          AND mfrodim.effective_to_dt =
                 (SELECT MAX (orgdim.effective_to_dt)
                    FROM organizations_dmn orgdim
                   WHERE mfrodim.organization_key_id =
                            orgdim.organization_key_id);
