CREATE OR REPLACE VIEW SCD.SCD_BLDG_PLANT_V
(building_id, building_nm, source_system_id)
AS
SELECT BUILDING_ID,BUILDING_NM,2 
	   FROM   GBL_BUILDINGS 
	   UNION 
	   SELECT GENERIC_CDE,CODE_NM,SOURCE_SYSTEM_ID 
	   FROM   CODE_LOOKUPS 
	   WHERE  CODE_TYPE_ID=7
;
