CREATE OR REPLACE VIEW SCD.SCD_SOURCE_SYSTEMS_V
(source_system_id, data_source_desc)
AS
SELECT TO_NUMBER(PARAMETER_FIELD),PARAMETER_ID 
	   	  FROM 	 DELIVERY_PARAMETER 
		  WHERE	 SUBSTR(PARAMETER_DESCRIPTION,1,6) = 'SRCSYS'
;
