INSERT INTO GSC.KEY_PERFORMANCE_INDICATORS (KPI_CDE, KPI_DESC, CERTIFIED_IND)
VALUES ('DCDS', 'Dock to Stock', 0);
COMMIT;

INSERT INTO GSC.KEY_PERFORMANCE_INDICATORS (KPI_CDE, KPI_DESC, CERTIFIED_IND)
VALUES ('TGTD', 'Gross on-time Delivery Carrier Performance', 0);
COMMIT;
