INSERT INTO GSC.KPI_METRICS (KPI_CDE, OPERATIONS_METRIC_CDE, TARGET_IND, TEOA_FUNCTIONAL_AREA_CDE)
values ('DCDS', 'DTS', 0, 'GLOG_REG');
COMMIT;

INSERT INTO GSC.KPI_METRICS (KPI_CDE, OPERATIONS_METRIC_CDE, TARGET_IND, TEOA_FUNCTIONAL_AREA_CDE)
values ('TGTD', 'GTP', 0, 'GLOG_REG');
COMMIT;
