INSERT INTO GSC.OPERATIONS_METRICS (OPERATIONS_METRIC_CDE, OPERATIONS_METRIC_DESC, KPI_METRIC_UNIT_CDE)
VALUES('DTS', 'Dock to Stock', 'NBR');
COMMIT;  

INSERT INTO GSC.OPERATIONS_METRICS (OPERATIONS_METRIC_CDE, OPERATIONS_METRIC_DESC, KPI_METRIC_UNIT_CDE)
VALUES('GTP', 'Gross on-time Delivery Carrier Performance', 'NBR');
COMMIT;  

