
-- 12/07/2012

ALTER TABLE GSC.UMS_ALERT_PREFERENCES
MODIFY
( PROFIT_CENTER_GROUP_ID NULL
, PROFIT_CENTER_ABBR_NM  NULL )
ADD ( REGION_ORGANIZATION_ID VARCHAR2(4) );

ALTER TABLE GSC.UMS_ALERT_PREFERENCES
DROP CONSTRAINT UMS_ALERT_PREFERENCES_UK1;

DROP INDEX UMS_ALERT_PREFERENCES_UK1;

ALTER TABLE GSC.UMS_ALERT_PREFERENCES
ADD CONSTRAINT UMS_ALERT_PREFERENCES_UK1
UNIQUE 
( NETWORK_ID, KPI_CDE
, KPI_METRIC_CDE
, PROFIT_CENTER_GROUP_ID
, PROFIT_CENTER_ABBR_NM
, TEOA_FUNCTIONAL_AREA_CDE
, REGION_ORGANIZATION_ID )
USING INDEX
TABLESPACE GSC_INDEX_A;

BEGIN
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'UMS_ALERT_PREFERENCES', estimate_percent => 20, method_opt => 'for all columns size 1', cascade => true, degree => 2 );
END;
/
