CREATE OR REPLACE VIEW SCD.GBL_INDUSTRY_GDS_DIM_V AS
SELECT
GIDDL_INDUSTRY_CODE INDUSTRY_CODE,
B.INDUSTRY_NAME INDUSTRY_NAME,
GIDDL_DD1_INDUSTRY_CODE DD1_INDUSTRY_CODE,
B1.INDUSTRY_NAME DD1_INDUSTRY_NAME,
GIDDL_DD2_INDUSTRY_CODE DD2_INDUSTRY_CODE,
B2.INDUSTRY_NAME DD2_INDUSTRY_NAME,
GIDDL_DD3_INDUSTRY_CODE DD3_INDUSTRY_CODE,
B3.INDUSTRY_NAME DD3_INDUSTRY_NAME,
GIDDL_DD4_INDUSTRY_CODE DD4_INDUSTRY_CODE,
B4.INDUSTRY_NAME DD4_INDUSTRY_NAME
FROM GBL_INDUSTRY_DRILL_DOWN_LAYERS A,
GBL_INDUSTRY B,
GBL_INDUSTRY B1,
GBL_INDUSTRY B2,
GBL_INDUSTRY B3,
GBL_INDUSTRY B4
WHERE A.GIDDL_INDUSTRY_CODE=B.INDUSTRY_CODE
AND A.GIDDL_DD1_INDUSTRY_CODE=B1.INDUSTRY_CODE
AND A.GIDDL_DD2_INDUSTRY_CODE=B2.INDUSTRY_CODE
AND A.GIDDL_DD3_INDUSTRY_CODE=B3.INDUSTRY_CODE
AND A.GIDDL_DD4_INDUSTRY_CODE=B4.INDUSTRY_CODE
;
