#!/bin/ksh
#set -x

###################################################################################################
# Name:    gscu2008
# Purpose: Populate KPI summaries for the GLOG DCPC Metrics (Productivity Cost Per Carton (TCSR/TCRT)).
# History:
#          08/01/2011  Kumar Emany       Original Version.
###################################################################################################

###################################################################################################
# Execute boiler plate to set environment
###################################################################################################

. /d013/project/gsc/scripts/gscu0000

###################################################################################################

JOBID=gscu2008
mmsg "Job $JOBID - Populate KPI summaries for the GLOG DCPC Metrics - Started." > $LOGDIR/$JOBID.log

RESULT=`sqlplus -s @$GSCSOURCEPASS <<EOF
SET SERVEROUTPUT ON;
SET FEEDBACK OFF;
WHENEVER OSERROR  exit 1
WHENEVER SQLERROR exit 1

DECLARE
   v_io_status   VARCHAR2(100);
   v_io_sqlcode  NUMBER;
   v_io_sqlerrm  VARCHAR2(2000);
BEGIN
   GSC_GLOG_KPI.DCPC_METRICS(v_io_status, v_io_sqlcode, v_io_sqlerrm);
   IF v_io_status != 'OK' then
      RAISE_APPLICATION_ERROR( -20001, 'SQLCODE:'||' '||v_io_sqlcode||' '||'SQLERRM:'||' '||v_io_sqlerrm);
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR( -20001, 'SQLCODE:'||' '||v_io_sqlcode||' '||'SQLERRM:'||' '||SQLERRM);
END;
/
EXIT
EOF`

if [ $? -ne 0 ]; then
   echo "$RESULT" >> $LOGDIR/$JOBID.log
   mmsg "Job $JOBID - Populate KPI summaries for the GLOG DCPC Metrics - Failed" >> $LOGDIR/$JOBID.log
   cat $LOGDIR/$JOBID.log
   mailx -s "Job $JOBID - $HOST_NAME - Populate KPI summaries for the GLOG DCPC Metrics - Failed" $GSC_Email <$LOGDIR/$JOBID.log
   exit 1;
fi

###################################################################################################

mmsg "Job $JOBID - Populate KPI summaries for the GLOG DCPC Metrics - Completed Successfully." >> $LOGDIR/$JOBID.log
cat $LOGDIR/$JOBID.log
mailx -s "Job $JOBID - $HOST_NAME - Populate KPI summaries for the GLOG DCPC Metrics - Completed Successfully." $GSC_Email <$LOGDIR/$JOBID.log

###################################################################################################

exit 0