connect SYS/change_on_install as SYSDBA
set echo on
spool /opt/db01/app/oracle/admin/SID/create/CreateDBTblSpcs.log

CREATE TABLESPACE "CCE_BILLING_DATA"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg01/db_SID_billing_data' SIZE 100M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE "CCE_BILLING_INDEX" INCLUDING CONTENTS;
CREATE TABLESPACE "CCE_BILLING_INDEX"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg02/db_SID_billing_index' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL;

spool off
exit;
