connect SYS/change_on_install as SYSDBA
set echo on
spool /opt/db01/app/oracle/admin/SID/create/CreateDBTblSpcs.log

DROP TABLESPACE "CCE_SERVICE_DATA" INCLUDING CONTENTS;
CREATE TABLESPACE "CCE_SERVICE_DATA"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg/db_SID_service_data' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE "CCE_SYS_COMP_DATA" INCLUDING CONTENTS;
CREATE TABLESPACE "CCE_SYS_COMP_DATA"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg/db_SID_cce_sys_comp_data' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE "CCE_LOG_DATA" INCLUDING CONTENTS;
CREATE TABLESPACE "CCE_LOG_DATA"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg/db_SID_log_data' SIZE 100M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 4000M EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE "CCE_SERVICE_INDEX" INCLUDING CONTENTS;
CREATE TABLESPACE "CCE_SERVICE_INDEX"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg/db_SID_service_index' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 250M EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE "CCE_SYS_COMP_INDEX" INCLUDING CONTENTS;
CREATE TABLESPACE "CCE_SYS_COMP_INDEX"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg/db_SID_cce_sys_comp_index' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 250M EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE "CCE_LOG_INDEX" INCLUDING CONTENTS;
CREATE TABLESPACE "CCE_LOG_INDEX"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg/db_SID_log_index_01' SIZE 100M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE "CCE_TEMP_DATA" INCLUDING CONTENTS;
CREATE TABLESPACE "CCE_TEMP_DATA"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg/db_SID_cce_temp_data' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 500M EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE "CCE_ARCH_DATA" INCLUDING CONTENTS;
CREATE TABLESPACE "CCE_ARCH_DATA"
  LOGGING DATAFILE '/dev/vx/rdsk/racdg/db_SID_cce_arch_data_01' SIZE 100M REUSE AUTOEXTEND ON NEXT  100M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL;

spool off
exit;
