connect SYS/change_on_install as SYSDBA
set echo on
spool /opt/db01/app/oracle/admin/SID/create/CreateDBFiles.log
CREATE TEMPORARY TABLESPACE "TEMP" TEMPFILE '/dev/vx/rdsk/racdg/db_SID_temp1' SIZE 200M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 1000M EXTENT MANAGEMENT LOCAL;
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE "TEMP";
CREATE UNDO TABLESPACE "UNDOTBS2" DATAFILE '/dev/vx/rdsk/racdg/db_SID_undotbs2' SIZE 500M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 1000M;
CREATE TABLESPACE "USERS" LOGGING DATAFILE '/dev/vx/rdsk/racdg/db_SID_users1' SIZE 100M REUSE AUTOEXTEND ON NEXT  10M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL;
spool off
exit;
