-- 01/03/2012

GRANT SELECT ON SDA_SUPPLIERS               TO ESP_SOURCE;

-- 12/19/2011

GRANT SELECT ON SUPPLIER_PARTS              TO ESP_SOURCE;
GRANT SELECT ON DISTINCT_ERP_SUPPLIER_PARTS TO ESP_SOURCE;

