 <% 
Dim sNavTopHeader
Dim sNavBotHeader
Dim sNavBorder
Dim sTitleColor

dim sTableHeadBg
dim sTableHeadFont
dim sTableBorder
dim sRow1color
dim sRow2color
dim sTblDataFont

dim sDisStrngFont2
dim sEndStrgFont2
dim sDisStrngFont
dim sEndStrgFont
dim sDisFont
dim sEndDisFont
dim sHr
dim sTDColor
dim sFontColor1
dim sFontColor2
dim sFontColor3


'This is for the Navigation 
sNavTopHeader = " bgcolor=White"
sNavBotHeader = " bgcolor=Navy"
sNavBorder = "Navy"
sTitleColor = " Color = White"

'This is used for generating result tables
sTableHeadBg = " bgcolor=Navy"
sTableHeadFont = " color = White"
sTableBorder = " bordercolor=lightgrey "
sRow1Color = " bgcolor=White"
sRow2Color = " bgcolor=Beige"
sTblDataFont = " color=Red"
sTDColor = " bgcolor=lightgrey"

'Font Colors
sFontColor1 = " color=navy"
sFontColor2 = " color=black"
sFontColor3 = " color=black"

'Big Fonts the color is navy
sDisStrngFont2 = "<font size=3" &  sFontColor1 & "><STRONG>"
sEndStrgFont2 = "</STRONG></font>"

'Fonts for bold the color is Navy
sDisStrngFont = "<font size=2" & sFontColor1 & "><STRONG>"
sEndStrgFont = "</STRONG></font>"

'Regular Fonts
sDisFont = "<font size=2" & sFontColor2 & ">"
sEndDisFont = "</font>"




'HR's (LINES)
sHR = "<hr color=#6699CC>"


  %>
  
 
