<%
'XLWindowState
Dim xlMaximized, xlMinimized, xlNormal
xlMaximized = -4137
xlMinimized = -4140
xlNormal = -4143

'XLChartType
Dim xl3DArea, xl3DAreaStacked, xl3DAreaStacked100, xl3DBarClustered, xl3DBarStacked
Dim xl3DBarStacked100, xl3DColumn, xl3DColumnClustered, xl3DColumnStacked, xl3DColumnStacked100, xl3DLine
Dim xl3DPie, xl3DPieExploded, xlArea, xlAreaStacked, xlAreaStacked100, xlBarClustered, xlBarOfPie
Dim xlBarStacked, xlBarStacked100, xlBubble, xlBubble3DEffect, xlColumnClustered, xlColumnStacked, xlColumnStacked100
Dim xlConeBarClustered, xlConeBarStacked, xlConeBarStacked100, xlConeCol, xlConeColClustered
Dim xlConeColStacked, xlConeColStacked100, xlCylinderBarClustered, xlCylinderBarStacked, xlCylinderBarStacked100
Dim xlCylinderCol, xlCylinderColClustered, xlCylinderColStacked, xlCylinderColStacked100, xlDoughnut, xlDoughnutExploded
Dim xlLine, xlLineMarkers, xlLineMarkersStacked, xlLineMarkersStacked100, xlLineStacked, xlLineStacked100
Dim xlPie, xlPieExploded, xlPieOfPie, xlPyramidBarClustered, xlPyramidBarStacked, xlPyramidBarStacked100
Dim xlPyramidCol, xlPyramidColClustered, xlPyramidColStacked, xlPyramidColStacked100
Dim xlRadar, xlRadarFilled, xlRadarMarkers, xlStockHLC, xlStockOHLC, xlStockVHLC, xlStockVOHLC
Dim xlSurface, xlSurfaceTopView, xlSurfaceTopViewWireframe, xlSurfaceWireframe, xlXYScatter
Dim xlXYScatterLines, xlXYScatterLinesNoMarkers, xlXYScatterSmooth, xlXYScatterSmoothNoMarkers
xl3DArea = -4098
xl3DAreaStacked = 78
xl3DAreaStacked100 = 79
xl3DBarClustered = 60
xl3DBarStacked = 61
xl3DBarStacked100 = 62
xl3DColumn = -4100
xl3DColumnClustered = 54
xl3DColumnStacked = 55
xl3DColumnStacked100 = 56
xl3DLine = -4101
xl3DPie = -4102
xl3DPieExploded = 70
xlArea = 1
xlAreaStacked = 76
xlAreaStacked100 = 77
xlBarClustered = 57
xlBarOfPie = 71
xlBarStacked = 58
xlBarStacked100 = 59
xlBubble = 15
xlBubble3DEffect = 87
xlColumnClustered = 51
xlColumnStacked = 52
xlColumnStacked100 = 53
xlConeBarClustered = 102
xlConeBarStacked = 103
xlConeBarStacked100 = 104
xlConeCol = 105
xlConeColClustered = 99
xlConeColStacked = 100
xlConeColStacked100 = 101
xlCylinderBarClustered = 95
xlCylinderBarStacked = 96
xlCylinderBarStacked100 = 97
xlCylinderCol = 98
xlCylinderColClustered = 92
xlCylinderColStacked = 93
xlCylinderColStacked100 = 94
xlDoughnut = -4120
xlDoughnutExploded = 80
xlLine = 4
xlLineMarkers = 65
xlLineMarkersStacked = 66
xlLineMarkersStacked100 = 67
xlLineStacked = 63
xlLineStacked100 = 64
xlPie = 5
xlPieExploded = 69
xlPieOfPie = 68
xlPyramidBarClustered = 109
xlPyramidBarStacked = 110
xlPyramidBarStacked100 = 111
xlPyramidCol = 112
xlPyramidColClustered = 106
xlPyramidColStacked = 107
xlPyramidColStacked100 = 108
xlRadar = -4151
xlRadarFilled = 82
xlRadarMarkers = 81
xlStockHLC = 88
xlStockOHLC = 89
xlStockVHLC = 90
xlStockVOHLC = 91
xlSurface = 83
xlSurfaceTopView = 85
xlSurfaceTopViewWireframe = 86
xlSurfaceWireframe = 84
xlXYScatter = -4169
xlXYScatterLines = 74
xlXYScatterLinesNoMarkers = 75
xlXYScatterSmooth = 72
xlXYScatterSmoothNoMarkers = 73

'XLRowCol
Dim xlColumns, xlRows
xlColumns = 2
xlRows = 1

'XLDateLabelsType
Dim xlDataLabelsShowBubbleSizes, xlDataLabelsShowLabel, xlDataLabelsShowLabelAndPercent, xlDataLabelsShowNone, xlDataLabelsShowPercent, xlDataLabelsShowValue
xlDataLabelsShowBubbleSizes = 6
xlDataLabelsShowLabel = 4
xlDataLabelsShowLabelAndPercent = 5
xlDataLabelsShowNone = -4142
xlDataLabelsShowPercent = 3
xlDataLabelsShowValue = 2

'XLChartLocation
Dim xlLocationAsNewSheet, xlLocationAsObject, xlLocationAutomatic
xlLocationAsNewSheet = 1
xlLocationAsObject = 2
xlLocationAutomatic = 3

'XLLegendPosition
Dim xlLegendPositionBottom, xlLegendPositionCorner, xlLegendPositionLeft, xlLegendPositionRight, xlLegendPositionTop
xlLegendPositionBottom = -4107
xlLegendPositionCorner = 2
xlLegendPositionLeft = -4131
xlLegendPositionRight = -4152
xlLegendPositionTop = -4160
%>